name: CI

on:
  push:
    branches:
      - "devel"
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: "Build binaries"
        run: make build
