name: Govuln
on: [ push, pull_request ]

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            Makefile
      - name: govulncheck
        env:
          GIT_TERMINAL_PROMPT: 1
          GOPRIVATE: github.com/0xPolygon/heimdall-v2
          GH_PAT_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: make vulncheck
        if: "env.GIT_DIFF != ''"
