name: Govuln
on: [ push, pull_request ]

jobs:
  govuln:
    name: Run govuln check and Publish
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/0xPolygon/heimdall-v2
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/checkout@v3
      - name: Running govulncheck
        uses: Templum/govulncheck-action@v1.0.1
        continue-on-error: false
        env:
          DEBUG: "true"
        with:
          go-version: 1.23.2
          package: ./...
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-vuln: true

      - name: Upload govulncheck report
        uses: actions/upload-artifact@v3
        with:
          name: raw-report
          path: raw-report.json
